#!/bin/bash
#SBATCH --job-name=modulus-test
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu=7000mb
#SBATCH --partition=gpu
#SBATCH --gpus=a100:8
#SBATCH --time=12:30:00

module purge
module load ufrc modulus

#srun --unbuffered --mpi=none -n 8 python lennard_jones_system.py
srun --mpi=none -n 8 python lennard_jones_system.py
